[package]
name = "rdocx-layout"
description = "Layout engine for converting DOCX flow model to positioned frames"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.release]
shared-version = "workspace"
tag-name = "v{{version}}"

[features]
default = ["system-fonts"]
system-fonts = ["oxml-layout/system-fonts"]

[dependencies]
oxml-chart = { workspace = true }
oxml-drawing = { workspace = true }
oxml-layout = { workspace = true, default-features = false }
rdocx-oxml = { workspace = true }
unicode-linebreak = { workspace = true }
